import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import Image from "next/image";
import Link from "next/link";
import Footer from "@/components/home/Footer";

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk.ttf",
  variable: "--font-space-grotesk",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routes = [
  { href: "/about-us", label: "About us" },
  { href: "/services", label: "Services" },
  { href: "/use-cases", label: "Use Cases" },
  { href: "/pricing", label: "Pricing" },
  { href: "/blog", label: "Blog" },
  { href: "/request-a-quote", label: "Request a quote" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased flex container mx-auto flex-col items-center pt-4 px-16 font-spaceGrotesk gap-10`}
      >
        <nav className="flex justify-between items-center w-full">
          <Link href="/">
            <Image src="/assets/logo.svg" alt="Logo" width={300} height={200} />
          </Link>
          <ul className="flex gap-8 items-center">
            {routes.map(({ href, label }) => (
              <li key={href}>
                <Link
                  href={href}
                  className={`font-medium text-xl ${
                    label === "Request a quote"
                      ? "border border-black py-5 px-7 rounded-lg"
                      : ""
                  }`}
                >
                  {label || href}{" "}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
